# ---------------------------------------------------------------------------
# dubbing/duration_match.py — Time-stretch Hindi audio to match original clip.
#
# PURPOSE:
#   After voice cloning, the Hindi audio is almost never the exact same
#   length as the original English clip (Hindi words may be shorter or
#   longer).  We need to time-stretch or compress the Hindi audio to fit
#   the original segment duration exactly.  This is critical because the
#   lip-sync step expects audio that is the same length as the video.
#
# WHY pyrubberband?
#   • Uses the Rubber Band Library under the hood — the industry standard
#     for pitch-preserving time-stretch (used by Audacity, Ableton, etc.).
#   • Does NOT change pitch when stretching — the speaker still sounds
#     natural, just slightly faster or slower.
#   • Alternatives like pydub's speedup() change pitch, making the voice
#     sound chipmunk-like or robotic.
#
# FALLBACK:
#   If pyrubberband / rubberband-cli is not installed, we fall back to
#   ffmpeg's atempo filter.  atempo also preserves pitch but has slightly
#   lower quality than Rubber Band.
#   atempo only supports factors between 0.5 and 2.0, so we chain
#   multiple atempo filters for extreme ratios.
#
# SCALABILITY NOTE:
#   Duration matching is CPU-bound and very fast (~10 ms per segment).
#   No special scaling considerations — this step is never the bottleneck.
# ---------------------------------------------------------------------------

import logging
import os
import subprocess

import soundfile as sf

logger = logging.getLogger(__name__)


def match_duration(
    audio_path: str,
    target_duration_sec: float,
    output_path: str,
) -> str:
    """
    Time-stretch or compress audio to exactly target_duration_sec.

    The pitch is preserved — the speaker's voice does not change,
    only the speed.  Think of it as "talking slightly faster/slower."

    Acceptable stretch range:  0.5× – 2.0× (beyond this quality degrades).
    For a 15-second clip this means the Hindi audio can be 7.5 s – 30 s
    and still produce good results.

    Args:
        audio_path          : Input WAV (generated by voice_clone.py).
        target_duration_sec : Desired output duration (= original clip length).
        output_path         : Where to write the time-stretched WAV.

    Returns:
        output_path on success.

    Raises:
        FileNotFoundError – input audio missing.
        RuntimeError      – stretch operation fails.
    """
    if not os.path.isfile(audio_path):
        raise FileNotFoundError(f"Audio file not found: {audio_path}")
    if target_duration_sec <= 0:
        raise ValueError(f"target_duration must be > 0, got {target_duration_sec}")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    # ── Measure current duration ─────────────────────────────────────────
    info = sf.info(audio_path)
    current_duration = info.duration  # seconds (float)

    if current_duration <= 0:
        raise RuntimeError(f"Input audio has 0 duration: {audio_path}")

    # ── Calculate stretch ratio ──────────────────────────────────────────
    # ratio > 1.0 → speed up (Hindi audio is longer than target)
    # ratio < 1.0 → slow down (Hindi audio is shorter than target)
    # ratio = 1.0 → no change needed
    stretch_ratio = current_duration / target_duration_sec

    logger.info(
        "Duration match: current=%.2fs → target=%.2fs (ratio=%.3f)",
        current_duration, target_duration_sec, stretch_ratio,
    )

    # ── Skip if already close enough (within 50 ms) ──────────────────────
    if abs(current_duration - target_duration_sec) < 0.05:
        logger.info("Already within 50 ms of target — copying as-is.")
        import shutil
        shutil.copy2(audio_path, output_path)
        return output_path

    # ── Warn on extreme ratios ───────────────────────────────────────────
    if stretch_ratio > 2.0 or stretch_ratio < 0.5:
        logger.warning(
            "Extreme stretch ratio %.2f — output quality may degrade. "
            "Consider splitting long segments for better results.",
            stretch_ratio,
        )

    # ── Try pyrubberband first (best quality) ────────────────────────────
    try:
        return _stretch_rubberband(audio_path, stretch_ratio, output_path)
    except Exception as e:
        logger.warning("pyrubberband failed (%s) — falling back to ffmpeg atempo.", e)

    # ── Fallback: ffmpeg atempo filter ───────────────────────────────────
    return _stretch_ffmpeg(audio_path, stretch_ratio, output_path)


def _stretch_rubberband(
    audio_path: str, ratio: float, output_path: str,
) -> str:
    """
    Pitch-preserving time-stretch using pyrubberband.

    pyrubberband is a thin Python wrapper around the Rubber Band Library
    (C++). It reads audio via soundfile, processes it, and writes back.

    The key function is pyrubberband.time_stretch(y, sr, rate):
      - rate > 1.0 → audio gets SHORTER (plays faster)
      - rate < 1.0 → audio gets LONGER  (plays slower)
    This is the INVERSE of what you might expect — "rate" means playback
    speed, not duration factor.  ratio = current / target is already in
    the correct direction (longer Hindi → rate > 1 → speed up).
    """
    import pyrubberband as pyrb

    # Read audio samples and sample rate
    audio_data, sample_rate = sf.read(audio_path)

    logger.debug("pyrubberband stretch: ratio=%.3f, sr=%d", ratio, sample_rate)

    # Time-stretch (pitch is preserved automatically)
    stretched = pyrb.time_stretch(audio_data, sample_rate, ratio)

    # Write output WAV
    sf.write(output_path, stretched, sample_rate)

    logger.info("Rubberband stretch done → %s", output_path)
    return output_path


def _stretch_ffmpeg(
    audio_path: str, ratio: float, output_path: str,
) -> str:
    """
    Pitch-preserving time-stretch using ffmpeg's atempo filter.

    atempo only accepts values in [0.5, 2.0].  For ratios outside this
    range we chain multiple atempo filters.
    Example: ratio=4.0 → atempo=2.0,atempo=2.0 (2.0 × 2.0 = 4.0).

    This is slightly lower quality than Rubber Band but works everywhere
    ffmpeg is installed (including Colab with zero extra setup).
    """

    # ── Build atempo filter chain ────────────────────────────────────────
    # atempo=ratio means "play at ratio× speed"
    # We need to split extreme ratios into chains of 0.5–2.0 each.
    filters = []
    remaining = ratio
    while remaining > 2.0:
        filters.append("atempo=2.0")
        remaining /= 2.0
    while remaining < 0.5:
        filters.append("atempo=0.5")
        remaining /= 0.5
    filters.append(f"atempo={remaining:.6f}")

    filter_str = ",".join(filters)

    cmd = [
        "ffmpeg", "-y",
        "-i", audio_path,
        "-filter:a", filter_str,
        "-acodec", "pcm_s16le",
        output_path,
    ]

    logger.debug("ffmpeg atempo cmd: %s", " ".join(cmd))

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"ffmpeg atempo failed (rc={result.returncode}):\n{result.stderr}"
        )

    logger.info("ffmpeg atempo stretch done → %s", output_path)
    return output_path
